In [1]:
import numpy as np
arr=np.array([1,2,3])
print(arr)

[1 2 3]


In [2]:
arr1=np.array((1,2,3))
print(arr1)

[1 2 3]


In [3]:
arr2=np.arange(16).reshape(4,4)
print(arr2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


#adding 10 to every element

In [4]:
#adding 10 to every element
arr2=arr2+10.1
print(arr2)

[[10.1 11.1 12.1 13.1]
 [14.1 15.1 16.1 17.1]
 [18.1 19.1 20.1 21.1]
 [22.1 23.1 24.1 25.1]]


In [5]:
#sum of all elements in array
print(arr2.sum())

281.6


In [6]:
#finding out datatype of array
print(arr2.dtype)

float64


In [7]:
a=np.array([[1,2,3],[4,5,6]],dtype="float")
print(a)
print(a.dtype)

[[1. 2. 3.]
 [4. 5. 6.]]
float64


In [8]:
arr3=np.array(((1,2,3),(4,5,6)),dtype="float")
print(arr3)

[[1. 2. 3.]
 [4. 5. 6.]]


In [9]:
#creating zeros 
arr4=np.zeros((3,4))
print(arr4)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [10]:
#creating random values
arr5=np.random.random((2,2))
print(arr5)

[[0.38096551 0.68194887]
 [0.31915641 0.41754633]]


In [11]:
# usage of linspace 
arr6=np.linspace(0,5,10)
print(arr6)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [12]:
#using flatten array
arr7=np.array([[1,2,3],[4,5,6]])
print(arr7.flatten()) #converted 2d into 1 d

[1 2 3 4 5 6]


# Indexing methods


In [42]:
arr8=np.arange(16).reshape(4,4)
print(arr8)
#indexing using interger indexing
temp=arr8[[1,3,0],[2,1,1]]
print()
print(temp)
cond=arr8>5
print()
print(arr8[cond]) #filtering with condition

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

[ 6 13  1]

[ 6  7  8  9 10 11 12 13 14 15]


In [14]:
#transpose of a above matrix
print(arr8.T)

[[ 0  4  8 12]
 [ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]]


In [44]:
#finding max,min,sum in array wrt axis
print(arr8)
print(arr8.min(axis=1))
print()
print(arr8.max(axis=0))
print()
print(arr8.sum(axis=1))


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[ 0  4  8 12]

[12 13 14 15]

[ 6 22 38 54]


In [16]:
# for matrix multiplication
print(arr8.dot(arr8))

[[ 56  62  68  74]
 [152 174 196 218]
 [248 286 324 362]
 [344 398 452 506]]


In [46]:
#sorting of array
arr8=np.array([[0,1,2,3],[-10,2,6,7],[8,9,-6,11],[12,1,14,15]])
print(arr8)
print()
print(np.sort(arr8,axis=None))
print()
print(np.sort(arr8,axis=1))
print()
print(np.sort(arr8,axis=0))

[[  0   1   2   3]
 [-10   2   6   7]
 [  8   9  -6  11]
 [ 12   1  14  15]]

[-10  -6   0   1   1   2   2   3   6   7   8   9  11  12  14  15]

[[  0   1   2   3]
 [-10   2   6   7]
 [ -6   8   9  11]
 [  1  12  14  15]]

[[-10   1  -6   3]
 [  0   1   2   7]
 [  8   2   6  11]
 [ 12   9  14  15]]


In [47]:
#sorting of structured array
dtypes=[("name",'S10'),("grad_year",int),("cgpa",float)]
values=[('varma',2018,8.02),('kalyan',2002,9),('mukesh',2020,8.5)]
arr=np.array(values,dtype=dtypes)
print(arr)
print()
#sorting using name
print(np.sort(arr,order="name"))
print()
print(np.sort(arr,order=["grad_year","cgpa"]))

[(b'varma', 2018, 8.02) (b'kalyan', 2002, 9.  ) (b'mukesh', 2020, 8.5 )]

[(b'kalyan', 2002, 9.  ) (b'mukesh', 2020, 8.5 ) (b'varma', 2018, 8.02)]

[(b'kalyan', 2002, 9.  ) (b'varma', 2018, 8.02) (b'mukesh', 2020, 8.5 )]


In [49]:
#stacking
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])

print(np.vstack((a,b))) #vertical stack

print()
print(np.hstack((a,b)))  #horizontal stack
print()

print(np.concatenate((a, b), 1)) #concatination using along 

[[1 2]
 [3 4]
 [5 6]
 [7 8]]

[[1 2 5 6]
 [3 4 7 8]]

[[1 2 5 6]
 [3 4 7 8]]


In [52]:
c=np.array([[1,2,34,55],[2,3,4,6]])
print(c)
print()
print(np.hsplit(c,2)) #horizontal split
print()
print(np.vsplit(c,2)) #vertical split

[[ 1  2 34 55]
 [ 2  3  4  6]]

[array([[1, 2],
       [2, 3]]), array([[34, 55],
       [ 4,  6]])]

[array([[ 1,  2, 34, 55]]), array([[2, 3, 4, 6]])]


In [54]:
#broadcasting
a = np.array([0.0, 10.0, 20.0, 30.0])
b = np.array([0.0, 1.0, 2.0])
print(a[:, np.newaxis] + b)

[[ 0.  1.  2.]
 [10. 11. 12.]
 [20. 21. 22.]
 [30. 31. 32.]]


In [57]:
#datetime
today = np.datetime64('2022-03-18')
print(today)
print(np.datetime64(today, 'Y')) #output year 
dates = np.arange('2022-02', '2022-03', dtype='datetime64[D]')
print(dates)
#sorting 
a = np.array(['2021-02-12', '2021-10-13', '2021-05-22'], dtype='datetime64')
print("\nDates in sorted order:", np.sort(a))

2022-03-18
2022
['2022-02-01' '2022-02-02' '2022-02-03' '2022-02-04' '2022-02-05'
 '2022-02-06' '2022-02-07' '2022-02-08' '2022-02-09' '2022-02-10'
 '2022-02-11' '2022-02-12' '2022-02-13' '2022-02-14' '2022-02-15'
 '2022-02-16' '2022-02-17' '2022-02-18' '2022-02-19' '2022-02-20'
 '2022-02-21' '2022-02-22' '2022-02-23' '2022-02-24' '2022-02-25'
 '2022-02-26' '2022-02-27' '2022-02-28']

Dates in sorted order: ['2021-02-12' '2021-05-22' '2021-10-13']


In [56]:
#data type objects for generating structured arrays

dt = np.dtype([('name', np.unicode_, 16),
               ('grades', np.float64, (2,))])
x = np.array([('Sarah', (8.0, 7.0)),
              ('John', (6.0, 7.0))], dtype=dt)

print(x[1])

print("Grades of John are: ", x[1]['grades'])
print("Names are: ", x['name'])

('John', [6., 7.])
Grades of John are:  [6. 7.]
Names are:  ['Sarah' 'John']


In [71]:
#Iterations using numpy.nditer 

a=np.array([[1,2,3],[7,3,2]])
for x in np.nditer(a, order = 'F'): 
    print(x,end=" ")
print()
for x in np.nditer(a, op_flags = ['readwrite']): #for changing the values of matrix
    x[...]= 5*x
    print(x)
print()
print("modified array")
print(a)

1 7 2 3 3 2 
5
10
15
35
15
10

modified array
[[ 5 10 15]
 [35 15 10]]


In [25]:
#Binary Operators
arr1 = np.array([2, 8, 125])
arr2 = np.array([3, 3, 115])
print(np.bitwise_and(arr1,arr2)) #using bitwise and operator
print(np.bitwise_or(arr1,arr2)) #using bitwise or operator
print(np.bitwise_xor(arr1,arr2)) #using bitwise xor

[  2   0 113]
[  3  11 127]
[ 1 11 14]


In [72]:
#binary representation of given number
print(np.binary_repr(10))

1010


In [73]:
#mathematical function
import math
arr1=[0,math.pi/4,math.pi/2,math.pi]
print(np.sin(arr1)) #using sine funciton which takes input in radians
print(np.cos(arr1)) #using cosine funciton which takes input in radians

[0.00000000e+00 7.07106781e-01 1.00000000e+00 1.22464680e-16]
[ 1.00000000e+00  7.07106781e-01  6.12323400e-17 -1.00000000e+00]


In [28]:
#round off numbers
arr2 = [.5538, 1.33354, .71445]
print(np.round(arr2,decimals=3))
print(np.floor(arr2))
print(np.exp(arr2))
print(np.log(arr2))

[0.554 1.334 0.714]
[0. 1. 0.]
[1.73985191 3.794452   2.04306269]
[-0.59095167  0.28783706 -0.33624226]


In [29]:
arr1 = np.array([2, 27, 2, 21, 23])
arr2 = np.array([2, 3, 4, 5, 6])
print(arr1/arr2)
print(np.divide(arr1,arr2))

[1.         9.         0.5        4.2        3.83333333]
[1.         9.         0.5        4.2        3.83333333]


In [30]:
#finding conjugate of complex numbers
arr1=np.array([4+5j,20+2j])
print("conjugate of arr1:",np.conj(arr1))
arr1 = np.array([1, 27000, 64, -1000])
print(np.cbrt(arr1)) #for finding cube root of given array

conjugate of arr1: [ 4.-5.j 20.-2.j]
[  1.  30.   4. -10.]


In [74]:
#clipping number below and above range 
in_array = np.array([1, 2, 3, 4, 5, 6, 7, 8 ])
print ("Input array : ", in_array)
 
out_array = np.clip(in_array, a_min = 2, a_max = 6)
print ("Output array : ", out_array)

Input array :  [1 2 3 4 5 6 7 8]
Output array :  [2 2 3 4 5 6 6 6]


In [75]:
arr2=np.array(["HELLO ","folks"])
print(np.char.lower(arr2))
print(np.char.split("HELLO Rowdies"))

['hello ' 'folks']
['HELLO', 'Rowdies']


In [79]:
#joining a string
arr1=np.array(['today is great', 'for'])
print(np.char.join(['-', ':'], ['today is great', 'for']))
print(np.char.join(['-', ':'], arr1))

#counting no of substring
print(np.char.count(arr1,'today'))
print(np.char.count(arr1,'for'))


['t-o-d-a-y- -i-s- -g-r-e-a-t' 'f:o:r']
['t-o-d-a-y- -i-s- -g-r-e-a-t' 'f:o:r']
[1 0]
[0 1]


In [77]:
a=np.array(['johny johny yes  papa', 'eating sugar', 'sugar no papa'])
 
# finding a higest index of substring or else returns -1 
print(np.char.rfind(a,'johny'))
 
# counting a substring
print(np.char.rfind(a, 'sugar'))

[ 6 -1 -1]
[-1  7  0]


In [35]:
A = np.array([[6, 1, 1],
              [4, -2, 5],
              [2, 8, 7]])
print("Rank of A:", np.linalg.matrix_rank(A))
print("\nTrace of A:", np.trace(A))
print("\nDeterminant of A:", np.linalg.det(A))
print("\nInverse of A:\n", np.linalg.inv(A))
print("\nMatrix A raised to power 3:\n",
           np.linalg.matrix_power(A, 3))

Rank of A: 3

Trace of A: 11

Determinant of A: -306.0

Inverse of A:
 [[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]

Matrix A raised to power 3:
 [[336 162 228]
 [406 162 469]
 [698 702 905]]


In [36]:
a = np.array([[-5,2],[-7,4]])
 
print("Array is :",a)
 
# calculating an eigen value
# using eig() function
c, d = np.linalg.eig(a)
 
print("Eigen value is :",c) #gives eigen values
print("Eigen value is :",d) #gives eigen vector


Array is : [[-5  2]
 [-7  4]]
Eigen value is : [-3.  2.]
Eigen value is : [[-0.70710678 -0.27472113]
 [-0.70710678 -0.96152395]]


In [37]:
#solving a linear equation
a = np.array([[1, 2], [3, 4]]) #coefficeinet of equation

b = np.array([8, 18]) #constants of equation
 
print(("Solution of linear equations:", 
      np.linalg.solve(a, b)))

('Solution of linear equations:', array([2., 3.]))


In [82]:
#sorting of an array using argsoft method

a = np.array([[10, 15], [12, 1]])
arr2 = np.sort(a, axis = -1)        
print ("\nAlong first axis : \n", arr2)
a = np.array([9, 3, 1, 7, 4, 3, 6])
print("a:",a)
b = np.argsort(a) #gives values of indices of sorted array
print("b:",b)
# To get sorted array using sorted indices
# c is temp array created of same len as of b
c = []
for i in range(0, len(b)):
    c.append(a[b[i]])
print('Sorted array->', c)



Along first axis : 
 [[10 15]
 [ 1 12]]
a: [9 3 1 7 4 3 6]
b: [2 1 5 4 6 3 0]
Sorted array-> [1, 3, 3, 4, 6, 7, 9]


In [81]:
#lexsort 
a = np.array([9, 3, 1, 3, 4, 3, 6])
 
# Second column 
b = np.array([4, 6, 9, 2, 1, 8, 7]) 
print('column a, column b')
for (i, j) in zip(a, b):
    print(i, ' ', j)

# Sort by a then by b
ind = np.lexsort((b, a)) 
print('Sorted indices->', ind)

column a, column b
9   4
3   6
1   9
3   2
4   1
3   8
6   7
Sorted indices-> [2 3 1 5 4 6 0]


In [80]:
array2 = np.array([[np.nan, 4,9], [1, 3,12]])
# returning Indices of the max element
# as per the indices ingnoring NaN
print(("\nIndices of max in array2 : ", np.nanargmax(array2)))

print(("\nIndices of min in array2 : ", np.nanargmin(array2))) #returning indices of min element

print("Number of nonzeros:",np.count_nonzero(array2))
a=np.array([[1,2,3],[0,0,3]])
print("Number of nonzeros:",np.count_nonzero(a))


('\nIndices of max in array2 : ', 5)
('\nIndices of min in array2 : ', 3)
Number of nonzeros: 6
Number of nonzeros: 4
